### ISSUE TITLE
Add jspsych locally

### ISSUE THREAD

**Issue by DominiqueMakowski** [RealityBending/IllusionGameValidation#1]
@anshu-97 just now was trying the game in the browser and it was taking time to load, saying `waiting for unpkg`. To prevent issues related to unpkg being down, we should probably download the modules, put them in the `utils` folder

https://github.com/RealityBending/IllusionGameValidation/blob/6658f3fd2828af3d1b0d21cff9317512f21f8073/index.html#L5-L13

and load them locally, so that we don't depend on a third party website

**Comment by anshu-97** [comment]
ooh I was using the third party so that we don't need to have so many things stored locally but if that's the case I'll store the plugins locally for fake face and resting state too?

**Comment by DominiqueMakowski** [comment]
> ooh I was using the third party so that we don't need to have so many things stored locally

In general it's good also because it forces us to stay up to date, but in this case just for reproducibility purposes maybe we can put everything locally so that the experiment will work regardless of jspsych's future updates

**Comment by DominiqueMakowski** [comment]
as in we can keep online for the IllusionGame basis, but locally for the actual experiments when they start running
